maps = [
    #This is the map where all of the variant randomizers are declared
    ("", "start", 010),
    #Additional randomizers are declared here, for enemies and such?
    ("", "Fortress_intro", 073),
    #RanLevel1_1, two maps are connected and 1=A for both, 2=B for both, 3=else B? So C and D will always go to B?
    ("Level 1 - Entrance", "level1_A", 001),
    ("Level 1 - Courtyard", "level1_2_A", 004),

    ("Level 1 - Entrance", "level1_B", 029),

    ("Level 1 - Entrance", "level1_C", 051),

    #IF Set_D IS ON:
    #Level 1 - Entrance = D, Level 2 Basement = B, and Level 5 - Mines = C
    #I haven't yet found what triggers "Set D" to be on, its a different variable than RanLevel1_1 and doesn't seem to be immediately declared in between
    #the initial randomization set and when it checks for Set D
    ("Level 1 - Entrance", "level1_D", 183),
    #RanLevel1_3
    ("Level 1 - Inner hall", "Level1_3_A", 003),

    ("Level 1 - Inner hall", "Level1_3_B", 031),

    ("Level 1 - Inner hall", "Level1_3_C", 053),

    #RanLevel3
    ("Level 3 - Prisons", "level3_A", 006),

    ("Level 3 - Prisons", "level3_B", 037),

    #unused
    #("Level 3 - Prisons", "level3_C", 059),
    #RanLevel4
    ("Level 4 - Caverns", "level4_A", 008),

    ("Level 4 - Caverns", "level4_B", 038),
    #RanLevel5
    ("Level 5 - Mines", "level5_A", 011),

    ("Level 5 - Mines", "level5_B", 039),

    ("Level 5 - Mines", "level5_C", 184),
    #Basement_2_variable
    ("Level 2 - Basement", "Level2_Basement_A", 077),

    ("Level 2 - Basement", "Level2_Basement_B", 182),
    #RanThicket2
    ("Level 3 - Thicket", "thicket_2_A", 019),

    ("Level 3 - Thicket", "thicket_2_B", 045),

    #unused
    #("Level 3 - Thicket", "thicket_2_C", 067),
    #RanThicket3
    ("Level 4 - Thicket", "thicket_3_A", 021),

    ("Level 4 - Thicket", "thicket_3_B", 046),

    
    # ("Level 7 - Catacombs", "level7_A", 024),
    # ("Ma'habre - The bridge", "Mahabre1_1_A", 026),
    # ("Ma'habre - Downtown", "Mahabre1_2_A", 027),
    # ("Level 6 - Mines", "level6_2_Crash", 030),
    # ("Level 2 - Shit pit", "toilet", 032),
    # ("Level 2 - Thicket", "thicket_1_B", 044),
    # ("Level 2 - Shit pit", "toilet", 054),
    # ("Level 5 - Thicket", "thicket_4_A", 060),
    # ("", "Hexen", 061),
    # ("Level 3 - Prisons", "Smash_pit", 062),
    # ("Rondon - Inside", "Rondon_inside2", 063),
    # ("", "MAP064", 064),
    # ("Level 9 - The gauntlet", "Level8_2_A", 065),
    # ("Level 2 - Thicket", "thicket_1_C", 066),
    # ("Level 5 - Thicket", "thicket_3_C", 068),
    # ("", "Staircase", 071),
    # ("", "MAP001", 072),
    # ("", "Fortress", 074),
    # ("Level 3 - Basement", "Level3_Basement_A", 075),
    # ("Level 1 - Stairway", "Level1_Basement_A", 076),
    # ("Temple of Torment - Level 1", "Temple of Torment", 078),
    # ("Temple of Torment - Level 2", "Temple of Torment_merc", 079),
    # ("Ma'habre - Back alleys", "Back_alleys", 080),
    # ("Temple of Torment - Level 2", "Temple of Torment_out", 081),
    # ("Temple of Torment - Level 2", "Temple of Torment_knight", 082),
    # ("Temple of Torment - Level 2", "Temple of Torment_dark", 083),
    # ("Temple of Torment - Level 2", "Temple of Torment_captain", 084),
    # ("Temple of Torment - Level 2", "Temple of Torment_empty", 085),
    # ("", "Fortress_ending", 086),
    # ("Ma'habre - Inside", "Mahabre_inside1", 087),
    # ("", "MAP088_tower", 088),
    # ("", "---center_square", 089),
    # ("Ma'habre 1 - The bridge", "---Mahabre1_1_A", 090),
    # ("", "MAP091", 091),
    # ("", "MAP092", 092),
    # ("Level 8 - The gauntlet", "Level8_A", 093),
    # ("Level 1 - Inner hall", "template_map1", 094),
    # ("Ma'habre 1 - The bridge", "temple_square", 095),
    # ("Ma'habre 1 - The bridge", "golden_temple", 096),
    # ("", "grand_library", 097),
    # ("", "grand_library2", 098),
    # ("", "golden_temple1", 099),
    # ("Ma'habre - Center square", "Center_square", 100),
    # ("Ma'habre - Passageway", "Passageway", 101),
    # ("Ma'habre - The Tower of Endless", "Ma'habre_Tower", 102),
    # ("Ma'habre - Temple district", "Temple_district", 103),
    # ("Grand library", "Grand_library", 104),
    # ("Grand library - Inner sanctum", "Grand_library_inner", 105),
    # ("Ma'habre - Pit of enlightenment", "pit_of_enlightenment", 106),
    # ("Ma'habre - Inside", "Mahabre_inside2", 107),
    # ("Ancient city - Passageway", "Ancient_Passageway", 108),
    # ("Ancient city - Center square", "Ancient_Center_square", 109),
    # ("Ancient city - Back alleys", "Ancient_Back_alleys", 110),
    # ("Ancient city - Downtown", "Ancient_1_2_A", 111),
    # ("Ancient city - The Tower of Endless", "Ancient_Tower", 112),
    # ("Ancient city - Temple district", "Ancient_Temple_district", 113),
    # ("Ancient city - Inside", "Ancient_inside2", 114),
    # ("Ancient city - Inside", "Ancient_inside1", 115),
    # ("Grand library", "Ancient_Grand_library", 116),
    # ("Grand library - Inner sanctum", "Ancient_Grand_library_inner", 117),
    # ("Ancient city - Pit of enlightenment", "Ancient_pit_of_enlightenment", 118),
    # ("Tower of Endless", "Tower of Endless", 119),
    # ("Tower of Endless", "Tower of Endless", 120),
    # ("Golden Temple", "Golden_temple", 121),
    # ("Temple of Torment - Level 1", "Ancient_Temple of Torment", 122),
    # ("Temple of Torment - Level 2", "Temple of Torment_level2", 123),
    # ("Flip side - Basement", "Flipside_Basement_A", 124),
    # ("Golden Temple - Inside", "Golden_temple_inside", 125),
    # ("Golden Temple", "Ancient_Golden_temple", 126),
    # ("Golden Temple - Inside", "Golden_temple_inside", 127),
    # ("Level 1 - Courtyard", "level1_2_B", 128),
    # ("", "Manhandle_scene", 129),
    # ("", "MAP130", 130),
    # ("", "Fortress", 131),
    # ("MAP131", "level1_A", 132),
    # ("The Kingdom of Rondon", "Dream_Rondon", 133),
    # ("Rondon - Inside", "Rondon_inside", 134),
    # ("Oldegård forests", "Dream_Oldegård", 135),
    # ("Oldegård - House", "Oldegård_house", 136),
    # ("Highlands", "Dream_highlands", 137),
    # ("", "Dream_final", 138),
    # ("Ancient city - Back alleys", "Ancient_cave_entrance", 139),
    # ("Next plane of existence", "Next_plane", 140),
    # ("Level 5 - Deeper thicket", "deeper_thicket", 141),
    # ("Level 9", "Level 9", 142),
    # ("Ancient city - Underground cave", "Ancient_cave", 143),
    # ("Grand hall", "Grand hall", 144),
    # ("Level 9 - The gauntlet", "Level9_trap", 145),
    # ("Golden Temple - Inside", "Golden_temple_inside2", 146),
    # ("", "MAP147", 147),
    # ("Ancient city - The Tomb of the Gods", "Ancient_tomb", 148),
    # ("The Tomb of the Gods - Level 2", "Ancient_tomb_gods", 149),
    # ("Ma'habre - The Tomb of the Gods", "Mahabre_tomb", 150),
    # ("The Tomb of the Gods - Level 2", "Mahabre_tomb_gods", 151),
    # ("", "fall_scene", 152),
    # ("Ma'habre - Underground cave", "Mahabre_Ancient_cave", 153),
    # ("Ancient city - The bridge", "Ancient1_1_A", 154),
    # ("Ancient city - Old passage", "Ancient_passage", 155),
    # ("", "MAP156", 156),
    # ("Ascended plane", "asc", 157),
    # ("", "School_1", 158),
    # ("Level 10 - The bottom", "Level 10", 159),
    # ("", "The_Void", 160),
    # ("", "Under_dungeon", 161),
    # ("", "RESULTS", 162),
    # ("Level 3 - Silent corridor", "Level3_Basement_Corridor", 163),
    # ("Ma'habre - Downtown", "Mahabre1_2_Book", 164),
    # ("Date - Caverns", "Caverns", 165),
    # ("Date - Tombs", "Tombs", 166),
    # ("Date - Blood pit", "Blood pit", 167),
    # ("The Kingdom of Rondon", "Overworld", 168),
    # ("", "Inside", 169),
    # ("", "dungeons", 170),
    # ("The Dungeons [LVL 1]", "Dungeons", 171),
    # ("The prisons [LVL 2]", "Prisons", 172),
    # ("", "School_4", 173),
    # ("The mines [LVL 3]", "Mines", 174),
    # ("Ancient city [LVL 4]", "Ancient_inside", 175),
    # ("", "Inside2", 176),
    # ("", "Inside3", 177),
    # ("", "School_2", 178),
    # ("", "School_3", 179),
    # ("", "School_5", 180),
    # ("Prom night!", "Prom", 181),
    # ("", "The_Void2", 185),
    # ("", "cave_in", 186),
]
